### ISSUE TITLE
"multiple, independent, well-substantiated reports" not attached to the letter

### ISSUE THREAD

**Issue by fralken** [scala-open-letter/scala-open-letter.github.io#266]
_"We state this based on multiple, independent, well-substantiated reports showing a systematic pattern of behavior over an extended period"_

Can you please attach these reports to the letter? Since you are dealing this delicate matter in the public, it would be a good idea, for transparency, to provide all the relevant information, so that the people can take an unbiased decision (to sign or not to sign the letter).

Thanks.

**Comment by keshavgbpecdelhi** [comment]
Is this a question or a task.

**Comment by SethTisue** [comment]
The letter already contains links to the information that the women involved have chosen to make public. There is some further corroboration if you follow various people on Twitter, and perhaps from other sources as well such as Reddit, but as far as I know nobody has done the work of assembling that into something that someone could just sit down and review.

There are now two kinds of names on this letter: the initial signers (of whom I was one), and then people who added their names later. Many of the initial signers were privately provided with additional documentation that we vouch for but are not authorized to make public.

If you're considering signing this letter, you'll have to make your own decision whether:

* the public information we have already linked to
* your trust in the original signers, should you happen to know any of us (some of us are available for private conversations to people we already have at least some level of knowledge and trust with)
* whatever additional information you can find on Twitter and elsewhere if you're willing to expend the effort

is sufficient for you to sign.

**Comment by JustinObserver** [comment]
> your trust in the original signers

I realize it may not be the same people bringing this forward, but please realize that this is a tall ask following the failed coupe attempt that was the RMS letter and the community has good reason to be skeptical until sufficient evidence comes to light.

**Comment by Augusta-Medus** [comment]
who is this person?

**Comment by SethTisue** [comment]
who is what person?

**Comment by fralken** [comment]
Thanks @SethTisue for the clarification. I agree that it is a good idea to separate original signers from additional supporters.

I also suggest you to add this part of your answer:

> If you're considering signing this letter, you'll have to make your own decision whether the following, in combination, are sufficient for you to decide to sign:
> 
> * the public information we have already linked to
> * your trust in the original signers, should you happen to know any of us (some of us are available for private conversations to people we already have at least some level of knowledge and trust with)
> * whatever additional information you can find on Twitter and elsewhere if you're willing to expend the effort

to the bottom of the letter near the link to the instructions for signing.

**Comment by bmc** [comment]
Speaking also for myself.

- There are two reports already public.
- Some of the original signers _may_ have some additional information which they are not at liberty to make public without compromising the potential safety of those involved. Don't expect them to budge on that point.
- We are in the process of separating the original signers from the members of the general public who signed after the letter was released, to make clearer that the wording of the letter comes from the original signers.
- If you do not trust the judgment of the original signers, some of whom are well known leaders in the community, then it's simple: Do not sign the open letter. Using objections to wording in this letter as a crowbar to pry out additional information will not work; we have no additional information we feel we can share publicly, and arguing is not going to change that fact.

Yifan and Vic went public. We support their stories. If that isn't enough, speaking (again) for myself, I'm sorry, but we have no more information to provide.

If there are additional victims who decide, on their own, to come forward, that will be and should be _entirely_ their decision.

**Comment by fralken** [comment]
Thanks @bmc . I agree that separating the original signers from additional supporters is the best solution to address my question. So that people can ask them or simply trust them for taking a decision to sign (or not sign) the letter.

**Comment by bmc** [comment]
Thanks. 

Just to be as clear as possible: Do not expect any of us to make any more information public, even if we have some. (And that is not an implied confirmation that we do. I do not have any additional verifiable reports, myself, and I will not speak for anyone else on the signers' list.)

This letter, and the victims' statements it supports, are all we are releasing. I'd advise not asking anyone for more. If any additional details are to be made public, they will be made public by the people involved.

**Comment by bmc** [comment]
FYI, I'm closing this issue.

**Comment by fancellu** [comment]
https://pretty.direct/impact
