### ISSUE TITLE
Should this not be removed, and replaced with an equally open and public apology to Jon by every signatory?

### ISSUE THREAD

**Issue by fancellu** [scala-open-letter/scala-open-letter.github.io#333]
https://pretty.direct/statement.html

https://pretty.direct/consentorder.pdf

**Comment by maffstephens** [comment]
This open letter is still public???

At least have the humility to post an update at the top.

**Comment by chrisbeach** [comment]
Disappointing to see these issues callously closed without answer by the "maintainer" of this repo.

Let's hope we can find a remedy via other legal means.

**Comment by fancellu** [comment]
https://pretty.direct/impact
